### ISSUE TITLE
Commit model.lua and mime.types?

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/snapCloud#12]
I don't get why these are in the gitignore (I know lapis adds them by default, but it doesn't make sense. lol).

mime.types is needed even to boot the app -- shouldn't it be included?
And I don't know too much about lapis, but the models seem like the type of thing to include too. :)

(I still haven't fully booted everything, but I think I've got it close now.)

**Comment by bromagosa** [comment]
Nope. Models and mimetypes are generated by Lapis and you should not include them in the repo. You need to follow the instructions in INSTALL.md to get Lapis to build those for you.

I think the only thing that's wrong in that file is that you'll need to first `mv nginx.conf` out of the cwd, run `lapis new --lua`, then move it back to the current dir.

I haven't had the time to update the instructions, I will when we do the next install from scratch. We can do that together so that you can follow along.

**Comment by cycomachead** [comment]
So, I think I did what you suggested with moving the Nguni conf file when I was trying to get things running. 
But from looking at the content of mime types, I can’t see why we wouldn’t keep it in the repo. (You don’t really want 2 different configurations.) and the models file isn’t even required. 

So if mimetypes is committed you can avoid running the new command.

**Comment by bromagosa** [comment]
Actually, you are right. I guess we could just include them in the repo, following what the most notorious real world Lapis app does:

https://github.com/luarocks/luarocks-site/blob/master/.gitignore

Do you want to to this? :)
