### ISSUE TITLE
Ability to Ban Users

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/snapCloud#136]
* Admins should be able to ban users
* banning should unlist all the user's projects
     * Should unlisting be determined by the project DB flags or just by the user data?
     * leaning towards the latter, and creating a single check for `can_access_project?` or something.

We don't need to worry about timing yet.

**Comment by cycomachead** [comment]
Yeah. I think we should extend it to the forum. 

I think there’s some parameters we can pass - though I’m not sure which exactly. I know discourse has a moderator parameter that we can now pass in addition to admin. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by bromagosa** [comment]
This is now done, except for the extension to the forum. Since you did the discourse module, can you take a look at it when you have some time?

It's waaaay down the line though. I think it may be okay to let banned users to have a say in the forum for a bit. We can always re-ban them there if they're incorrigible :stuck_out_tongue_closed_eyes:
