### ISSUE TITLE
PASSWORD in environment variable

### ISSUE THREAD

**Issue by TopNiz** [bromagosa/snapCloud#157]
Dear dev team,
I'm surprised to find that database password is stored as an environment variable. At least, can it be hashed and encrypted before putting as env variable ?

**Comment by cycomachead** [comment]
The database password only lives on the server where the app is deployed. (Well, technically, and in a secure password vault).  But only a couple of us managing the site have access to those credentials and the server. We follow the `.env` convention for locally defining environment variables (including launching the app) and that file is never committed. Each developer maintains their own env configuration, which contains local data. I don't see a reason to encrypt password, but I'd be interested in learning more.

Based on my experience deploying and managing other applications, environment variables are a safe enough way to configure applications. (Heroku does this, plenty of other apps use environment variables.)

Encrypting the password would essentially mean that you need a password+key on the app server to connect to the db. How would we pass in the key? It'd be an environment variable, or a path to a file -- but you're basically just requiring two pieces of info instead of one. While that sounds somewhat better, it's two pieces that are simply going to travel together.
