### ISSUE TITLE
Activation Emails Use Cloud Domain

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/snapCloud#228]
Easy fix, but we should change this.

**Comment by bromagosa** [comment]
That's right. It's been a while since I looked at this, but my recollection is that these URLs are being generated by `build_url`, and this function just appends the return value of `url_for` to the current application URL.

So my understanding is that the current application URL is still being read as `cloud.snap.berkeley.edu`. I'm guessing this would be as easy as getting rid of the `cloud` prefix in `ngingx.conf.d/ssl-production.conf`. Right?

**Comment by cycomachead** [comment]
OK, what I did was this in the `.env` file. The HOSTNAME is what build_url is reading.

```
export HOSTNAME="snap.berkeley.edu"
export SECONDARY_HOSTNAME="cloud.snap.berkeley.edu snap-cloud.cs10.org"
```

The secondary name tells nginx the other valid server names.

I think we should definitely keep the cloud.snap url accessible since there still seem to be things hitting it, and with the way things are configured right now, there's no real harm to having it up. :)

Gonna close this for now and re-think about #227 which I thought I had already done. :(

**Comment by bromagosa** [comment]
Cool! :)
