### ISSUE TITLE
mail system

### ISSUE THREAD

**Issue by bromagosa** [bromagosa/snapCloud#3]

**Comment by cycomachead** [comment]
I think the best thing will probably be to use a 3rd party service.

Amazon SES and Mailgun are both reliable, pretty cheap and have simple lua wrappers. (The mailgun api is pretty easy, and SES is OK, but has an annoying auth flow, so that library is helpful)
https://github.com/leafo/lua-mailgun
https://github.com/paragasu/lua-resty-aws-email

**Comment by cycomachead** [comment]
I can help once I figure out how to get my Mac running everything...

**Comment by bromagosa** [comment]
Hey, we got that working on the Beetle Cloud thanks to @backface, and he's done that before for the TurtleStitch site. As I said before, we just need an STMP provider, Lapis knows how to handle email, we don't need to use anything fancier (or more expensive) than that.

**Comment by cycomachead** [comment]
I've got something setup.

**Comment by bromagosa** [comment]
I found a bunch of rocks that may be of use. These are the ones that seem to make things easier, and they are both designed to work in an Nginx/OpenResty installation:

https://github.com/athersharif/lua-resty-smtp

https://github.com/GUI/lua-resty-mail

I'll test them both today and see which one works better :)

**Comment by bromagosa** [comment]
Yay! `lua-resty-mail` was the way to go. The dev is the same that made `lua-auto-ssl`. I love this guy :)
