### ISSUE TITLE
SSO integration with forum

### ISSUE THREAD

**Issue by bromagosa** [bromagosa/snapCloud#7]
@cycomachead can help :)

**Comment by bromagosa** [comment]
@cycomachead is the forum still up? I can't seem to access it anymore.

**Comment by cycomachead** [comment]
Oh no it's not. I think I can figure out how to restart it...

**Comment by bromagosa** [comment]
Any chance we can get the forum back? I'd like to start looking into the SSO thing :)

**Comment by bromagosa** [comment]
@cycomachead ping?

**Comment by cycomachead** [comment]
Sorry I haven’t had a chance. There’s always been more pressing work. 

(Also I don’t think we need a forum right away. I don’t feel good about increasing the surface area of what we need to monitor and provide support for until things stabilize a bit.)

Pulling in @brianharvey to see what he thinks. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by brianharvey** [comment]
On 3/15/18 12:02 PM, Michael Ball wrote:
> Sorry I haven’t had a chance. There’s always been more pressing work.
> 
> (Also I don’t think we need a forum right away. I don’t feel good about increasing the surface area of what we need to monitor and provide support for until things stabilize a bit.)
> 
> Pulling in @brianharvey to see what he thinks.

Way below backups.  :-)

I've been thinking of the forum as part of the general social-site rollout 
over the summer.  And I'm still terrified about moderating the site, 
including the forum.

"Surface area" is a nice metaphor.

**Comment by cycomachead** [comment]
Reference discourse docs: https://meta.discourse.org/t/official-single-sign-on-for-discourse-sso/13045

- we don't need to verify emails because those are false.

We'll send back and email, username, and user id.

Task list:
- [ ] lapis endpoint to receive SSO requests
- [ ] endpoint validates URL params
- [ ] render from w/ login info
- [ ] ensure user login works
- [ ] build new SSO callback request
- [ ] redirect back to discourse

**Comment by brianharvey** [comment]
Slightly off-topic, but this made me think:  In a perfect world, in which 
everyone were nice, we could establish emails foo@snap.b.e for all our 
users that forward to the address they gave us to establish their accounts, 
and users could then email each other directly, without our intervention.

I hate the 21st Century.

**Comment by brianharvey** [comment]
Why would anyone want users not to communicate directly?  Answer:  Because 
you're afraid one of them is a child molester.  That's the only good 
reason.  So, as I said, in a world in which everyone is nice...

**Comment by cycomachead** [comment]
I’d pick bullies as number one. 

But anyway, my question was more about why or if _email_ was the critical part of that direct communication. 

If we let users email each other we probably wouldn’t have an issue! Kids don’t use email. But if we let them text each other... then we’d have issues. 

But regardless, a forum gives us the option to email private communication, in a way that’s not email and no text. so it might get some usage. And we can monitor it. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by brianharvey** [comment]
I just thought of email because Bernat(?) posted that note about verified 
emails to avoid security holes and you(?) posted that we don't have to 
worry about that and that just started me thinking about email, and /that/ 
started me thinking about wishing I lived in a better world.

We now return to your technical discussion in progress...
